ALTER TABLE certificate
DROP COLUMN 
    LMK_KEY,
    ADDRESS2,
    POSTCODE,
    CONSTITUENCY,
    HOT_WATER_ENERGY_EFF,
    HOT_WATER_ENV_EFF,
    WINDOWS_ENERGY_EFF,
    WINDOWS_ENV_EFF,
    WALLS_ENERGY_EFF,
	NUMBER_HABITABLE_ROOMS,
	NUMBER_HEATED_ROOMS,
	LOW_ENERGY_LIGHTING,
    WALLS_ENV_EFF,
    MAINHEAT_ENERGY_EFF,
    MAINHEAT_ENV_EFF,
    MAINHEATC_ENERGY_EFF,
    MAINHEATC_ENV_EFF,
    LIGHTING_ENERGY_EFF,
    LIGHTING_ENV_EFF,
    WIND_TURBINE_COUNT,
    FLOOR_HEIGHT,
    ADDRESS,
    LOCAL_AUTHORITY_LABEL,
    CONSTITUENCY_LABEL,
    POSTTOWN;

SELECT
    SUM(CASE WHEN CURRENT_ENERGY_RATING IS NULL THEN 1 ELSE 0 END) AS CURRENT_ENERGY_RATING_Nulls,
    SUM(CASE WHEN POTENTIAL_ENERGY_RATING IS NULL THEN 1 ELSE 0 END) AS POTENTIAL_ENERGY_RATING_Nulls,
    SUM(CASE WHEN CURRENT_ENERGY_EFFICIENCY IS NULL THEN 1 ELSE 0 END) AS CURRENT_ENERGY_EFFICIENCY_Nulls,
    SUM(CASE WHEN POTENTIAL_ENERGY_EFFICIENCY IS NULL THEN 1 ELSE 0 END) AS POTENTIAL_ENERGY_EFFICIENCY_Nulls,
    SUM(CASE WHEN PROPERTY_TYPE IS NULL THEN 1 ELSE 0 END) AS PROPERTY_TYPE_Nulls,
    SUM(CASE WHEN BUILT_FORM IS NULL THEN 1 ELSE 0 END) AS BUILT_FORM_Nulls,
    SUM(CASE WHEN TRANSACTION_TYPE IS NULL THEN 1 ELSE 0 END) AS TRANSACTION_TYPE_Nulls,
    SUM(CASE WHEN ENVIRONMENT_IMPACT_CURRENT IS NULL THEN 1 ELSE 0 END) AS ENVIRONMENT_IMPACT_CURRENT_Nulls,
    SUM(CASE WHEN ENVIRONMENT_IMPACT_POTENTIAL IS NULL THEN 1 ELSE 0 END) AS ENVIRONMENT_IMPACT_POTENTIAL_Nulls,
    SUM(CASE WHEN ENERGY_CONSUMPTION_CURRENT IS NULL THEN 1 ELSE 0 END) AS ENERGY_CONSUMPTION_CURRENT_Nulls,
    SUM(CASE WHEN ENERGY_CONSUMPTION_POTENTIAL IS NULL THEN 1 ELSE 0 END) AS ENERGY_CONSUMPTION_POTENTIAL_Nulls,
    SUM(CASE WHEN CO2_EMISSIONS_CURRENT IS NULL THEN 1 ELSE 0 END) AS CO2_EMISSIONS_CURRENT_Nulls,
    SUM(CASE WHEN CO2_EMISSIONS_POTENTIAL IS NULL THEN 1 ELSE 0 END) AS CO2_EMISSIONS_POTENTIAL_Nulls,
    SUM(CASE WHEN LIGHTING_COST_CURRENT IS NULL THEN 1 ELSE 0 END) AS LIGHTING_COST_CURRENT_Nulls,
    SUM(CASE WHEN LIGHTING_COST_POTENTIAL IS NULL THEN 1 ELSE 0 END) AS LIGHTING_COST_POTENTIAL_Nulls,
    SUM(CASE WHEN HEATING_COST_CURRENT IS NULL THEN 1 ELSE 0 END) AS HEATING_COST_CURRENT_Nulls,
    SUM(CASE WHEN HEATING_COST_POTENTIAL IS NULL THEN 1 ELSE 0 END) AS HEATING_COST_POTENTIAL_Nulls,
    SUM(CASE WHEN HOT_WATER_COST_CURRENT IS NULL THEN 1 ELSE 0 END) AS HOT_WATER_COST_CURRENT_Nulls,
    SUM(CASE WHEN HOT_WATER_COST_POTENTIAL IS NULL THEN 1 ELSE 0 END) AS HOT_WATER_COST_POTENTIAL_Nulls,
    
    SUM(CASE WHEN CONSTRUCTION_AGE_BAND IS NULL THEN 1 ELSE 0 END) AS CONSTRUCTION_AGE_BAND_Nulls
FROM certificate;


DELETE FROM certificate
WHERE CURRENT_ENERGY_RATING IS NULL
   OR POTENTIAL_ENERGY_RATING IS NULL
   OR CURRENT_ENERGY_EFFICIENCY IS NULL
   OR POTENTIAL_ENERGY_EFFICIENCY IS NULL
   OR PROPERTY_TYPE IS NULL
   OR BUILT_FORM IS NULL
   OR TRANSACTION_TYPE IS NULL
   OR ENVIRONMENT_IMPACT_CURRENT IS NULL
   OR ENVIRONMENT_IMPACT_POTENTIAL IS NULL
   OR ENERGY_CONSUMPTION_CURRENT IS NULL
   OR ENERGY_CONSUMPTION_POTENTIAL IS NULL
   OR CO2_EMISSIONS_CURRENT IS NULL
   OR CO2_EMISSIONS_POTENTIAL IS NULL
   OR LIGHTING_COST_CURRENT IS NULL
   OR LIGHTING_COST_POTENTIAL IS NULL
   OR HEATING_COST_CURRENT IS NULL
   OR HEATING_COST_POTENTIAL IS NULL
   OR HOT_WATER_COST_CURRENT IS NULL
   OR HOT_WATER_COST_POTENTIAL IS NULL
   OR CONSTRUCTION_AGE_BAND IS NULL;

    SELECT 
    SUM(CASE WHEN PROPERTY_TYPE = 'NO DATA!' THEN 1 ELSE 0 END) AS PROPERTY_TYPE_NO_DATA,
    SUM(CASE WHEN BUILT_FORM = 'NO DATA!' THEN 1 ELSE 0 END) AS BUILT_FORM_NO_DATA,
    SUM(CASE WHEN TRANSACTION_TYPE = 'NO DATA!' THEN 1 ELSE 0 END) AS TRANSACTION_TYPE_NO_DATA,
    SUM(CASE WHEN CONSTRUCTION_AGE_BAND = 'NO DATA!' THEN 1 ELSE 0 END) AS CONSTRUCTION_AGE_BAND_NO_DATA
FROM certificate;



UPDATE certificate
SET BUILT_FORM = NULL
WHERE BUILT_FORM = 'NO DATA!';

UPDATE certificate
SET CONSTRUCTION_AGE_BAND = NULL
WHERE CONSTRUCTION_AGE_BAND = 'NO DATA!';

DELETE FROM certificate
WHERE BUILT_FORM IS NULL
   OR CONSTRUCTION_AGE_BAND IS NULL
   OR PROPERTY_TYPE IS NULL
   OR TRANSACTION_TYPE IS NULL;


select * from certificate